research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

web_search_task:
  description: >
    Search the web for information related to the user's query: "{query}"
    Find the most relevant and up-to-date information from reliable sources.
    Focus on answering the specific question or topic the user is interested in.
  expected_output: >
    A list of search results with titles, snippets, and URLs that are most relevant to the query.
    Include a brief explanation of why each result is relevant.
  agent: web_researcher

web_scraping_task:
  description: >
    Extract information from the following URLs: {urls}
    Focus on extracting the most relevant content that helps answer the user's query: "{query}"
    Be thorough but concise in your extraction.
  expected_output: >
    A summary of the extracted information from each URL, highlighting the most relevant parts
    that help answer the user's query.
  agent: web_researcher

content_analysis_task:
  description: >
    Analyze the following content to extract key information: {content}
    Identify the main points, key facts, and any insights that are relevant to the user's query: "{query}"
  expected_output: >
    A structured analysis of the content, including:
    1. A summary of the main points
    2. Key facts and figures
    3. Important insights or conclusions
    4. Any conflicting information or areas of uncertainty
  agent: content_analyzer

news_aggregation_task:
  description: >
    Find recent news articles related to the topic: "{query}"
    Focus on the most recent and relevant news from the past {days} days.
  expected_output: >
    A list of recent news articles with titles, summaries, sources, and publication dates.
    Include a brief explanation of how each article relates to the user's query.
  agent: web_researcher

report_creation_task:
  description: >
    Create a comprehensive research report based on all the information gathered.
    The report should directly answer the user's query: "{query}"
    Organize the information in a logical and easy-to-understand format.
  expected_output: >
    A well-structured research report that answers the user's query.
    The report should include:
    1. An executive summary
    2. Main findings and insights
    3. Supporting evidence and data
    4. Conclusions and recommendations
    Format the report in markdown.
  agent: report_writer
